spring:
    main:
        web-application-type: none
    ai:
        dashscope:
            api-key: ${AI_DASHSCOPE_API_KEY}
            chat:
                options:
                    model: qwen-plus
        mcp:
            client:
                stdio:
                    servers-configuration: classpath:/mcp-servers-config.json

    application:
        name: mcp-filesystem
logging:
    level:
        root: info
        org.springframework.ai.chat.client.advisor: DEBUG
